### ISSUE TITLE
Is G-engine compatible with SWAT 3 ? 

### ISSUE THREAD

**Issue by AnthraxBass** [kromenak/gengine#12]
Based on some old articles I have figured out, that SWAT 3 was based on GK engine, so the question is - how similar they are?

**Comment by AnthraxBass** [comment]
@kromenak Thank you so much, the articles are really good ! 
P.S. offtopic: Is there a chance you know of some SWAT3 R.E. project ?

**Comment by kromenak** [comment]
No sorry - haven't heard of any SWAT 3 projects.
