### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by neuromancer** [kromenak/gengine#5]
I think people will be more interested in testing this neat re-implementation and maybe collaborate with some code if you show the current state of this reimplementation in the README. Even early screenshots are fine!

**Comment by kromenak** [comment]
Hi, I added a "Progress" section to the README. Also, there is a "Media" folder that contains some screenshots. 

The engine is further along than my blog might suggest, but there's still a lot of work to go. However, I hope you'll agree that at least graphically, it's getting close to the original game.
