### ISSUE TITLE
win build?

### ISSUE THREAD

**Issue by necros2k7** [kromenak/gengine#6]
subj

**Comment by kromenak** [comment]
Hi, I recently updated the README to explain how to build the project on Windows using Visual Studio 2019, which is free to download here: https://visualstudio.microsoft.com/downloads/

I know it's annoying to have to build from source - I'm working on figuring out the build/versioning pipeline so I can start posting releases directly on GitHub. But for the time being, your best best will be to download the source and build it locally.

**Comment by necros2k7** [comment]
Yes, maybe Appveyor can be used?

**Comment by kromenak** [comment]
Thanks for the tip - I haven't used Appveyor before, but it looks like it'll probably be a good solution. I'll see if I can't get something up and running in the next couple weeks.

**Comment by kromenak** [comment]
Hi, I've set up a CI pipeline using CMake and Appveyor. From time to time, as meaningful new features are added to the engine, I'll make Win/Mac builds and deploy them via GitHub. You can find those releases here: https://github.com/kromenak/gengine/releases

I also updated the README with a few instructions on running the game. Game controls are the same as the original game for the most part. One important note is that you can use F4 to force-quite the game (in-game menus are not yet implemented).
